apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: flight-viz
data:
  RAILS_ENV: "production"
  DATABASE_HOST: "database-service"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
