{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  labels:
    {{- include "flight-viz.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.certManager.issuer.server }}
    email: {{ .Values.certManager.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.name }}-private-key
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className }}
{{- end }}
