apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flight-viz.backend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flight-viz.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  RAILS_ENV: {{ .Values.env.rails.environment }}
  DATABASE_HOST: {{ include "flight-viz.postgresql.fullname" . }}
  DATABASE_NAME: {{ .Values.postgresql.auth.database }}
