{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-viz.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flight-viz.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.registry.server .Values.registry.username .Values.registry.password (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
{{- end }}
