apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flight-viz.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flight-viz.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
